version: '3.8'

services:
  mcsv_productos_db:
    container_name: mcsv_productos
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: productos_microservice_db
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./data/db:/var/lib/mysql

  springboot_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    restart: unless-stopped
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mcsv_productos_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mcsv_productos:3306/productos_microservice_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
